package com.qinghe.marketing.shared.error;

public enum QingheErrorCode {
    INVALID_ARGUMENT(400),
    TOKEN_INVALID(401),
    TOKEN_EXPIRED(401),
    UNAUTHENTICATED(401),
    FORBIDDEN(403),
    MEMBER_FROZEN(403),
    MEMBER_CANCELLED(403),
    RESOURCE_NOT_FOUND(404),
    REQUEST_CONFLICT(409),
    IDEMPOTENCY_CONFLICT(409),
    STORE_IMPORT_CONFLICT(409),
    BUSINESS_STATE_CONFLICT(409),
    CAMPAIGN_STATE_CONFLICT(409),
    VERSION_CONFLICT(409),
    SELF_APPROVAL_NOT_ALLOWED(409),
    TEMPLATE_VERSION_LOCKED(409),
    CAMPAIGN_INCOMPLETE(422),
    ALREADY_CLAIMED(409),
    SOLD_OUT(409),
    CAMPAIGN_NOT_ACTIVE(422),
    STORE_NOT_ELIGIBLE(422),
    SIGNATURE_INVALID(401),
    REQUEST_EXPIRED(401),
    RIGHT_NOT_FOUND(409),
    RIGHT_NOT_AVAILABLE(409),
    RIGHT_EXPIRED(409),
    STORE_NOT_APPLICABLE(409),
    ALREADY_REDEEMED(409),
    REDEMPTION_NOT_FOUND(404),
    RATE_LIMITED(429),
    SYSTEM_BUSY(503),
    TEMPORARY_UNAVAILABLE(503),
    EXTERNAL_SERVICE_UNAVAILABLE(503),
    INTERNAL_ERROR(500);

    private final int httpStatus;

    QingheErrorCode(int httpStatus) {
        this.httpStatus = httpStatus;
    }

    public int httpStatus() {
        return httpStatus;
    }
}
